"""
Seed Technical Tasks with realistic sample data matching Inhyma ERP legacy screens.
"""

import asyncio
import sys
from pathlib import Path

# Add backend directory to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from datetime import date
from decimal import Decimal
import uuid

from sqlalchemy import select
from app.database.engine import get_sessionmaker
from app.technical_tasks.models import TechnicalTask

SAMPLE_TASKS = [
    {
        "company_name": "S.K. PACKAGING",
        "task_type": "In-House",
        "city": "Ambarnath",
        "third_party": None,
        "priority": "A",
        "machine_model": "XM12.7 Handy Printer Metal Body 12.7mm",
        "task_description": "Handy printer cartridge maintenance and ink jet alignment check. Customer requested nozzle cleaning and test prints on corrugated boxes.",
        "contact_person_name": "Sonu Kashyap",
        "contact_phone": "8767069077",
        "contact_designation": None,
        "created_by_name": "Siddhi Kilaje",
        "task_created_date": date(2026, 9, 17),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Demo",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 17),
        "task_allotted_to": "Devendra Pandey",
        "payment_status": None,
        "status": "Completed",
        "completed_date": date(2026, 9, 17),
    },
    {
        "company_name": "Mahadev Enterprises (M)",
        "task_type": "Onsite Visit - Client Location",
        "city": "Kalyan-Dombivli",
        "third_party": "Kalyan-Dombivli",
        "priority": "A",
        "machine_model": "DZ500 MS External Vacuum Machine",
        "task_description": "Vacuum pump oil leakage and seal heating element replacement needed. Onsite visit required for chamber pressure calibration.",
        "contact_person_name": "Hari Gupta",
        "contact_phone": "9920958355",
        "contact_designation": None,
        "created_by_name": "Siddhi Kilaje",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Chargeable",
        "service_charge": Decimal("4500.00"),
        "call_type": "Repair",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 17),
        "task_allotted_to": "Mangal Pandey",
        "payment_status": "Pending",
        "status": "Approved",
        "completed_date": None,
    },
    {
        "company_name": "Kamal Packaging",
        "task_type": "In-House",
        "city": "Mumbai",
        "third_party": None,
        "priority": "A",
        "machine_model": "AF250CS Auger Servo Base 340mm",
        "task_description": "Sample pouch filling trial for fine turmeric and spice powder. Test weighing accuracy and dust extraction hood setup.",
        "contact_person_name": "JAYASHREE WAMAN KAMBLE",
        "contact_phone": "8108752149",
        "contact_designation": None,
        "created_by_name": "Siddhi Kilaje",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": None,
        "task_approved_date": None,
        "task_allotted_to": None,
        "payment_status": None,
        "status": "Pending",
        "completed_date": None,
    },
    {
        "company_name": "MANDAGINI AGENCIES",
        "task_type": "In-House",
        "city": "Bhiwandi",
        "third_party": None,
        "priority": "A",
        "machine_model": "KH90 Semi Auto Strapping Machine",
        "task_description": "Demonstration of PP strap tension control and heat sealing cycle for carton packaging dispatch.",
        "contact_person_name": "Rakesh Verma",
        "contact_phone": "9820123456",
        "contact_designation": "Purchase Head",
        "created_by_name": "Dhairya Shah",
        "task_created_date": date(2026, 9, 15),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Demo",
        "task_approved_by": None,
        "task_approved_date": None,
        "task_allotted_to": None,
        "payment_status": None,
        "status": "Pending",
        "completed_date": None,
    },
    {
        "company_name": "UNIQUE ENTERPRISES",
        "task_type": "Onsite Visit - Client Location",
        "city": "Navi Mumbai",
        "third_party": None,
        "priority": "A",
        "machine_model": "A14/2.5TD Multi Head Weigher With Timing Hopper",
        "task_description": "Timing hopper synchronisation with collar form-fill-seal unit. Inspect load cell calibration for dry fruit packaging.",
        "contact_person_name": "DEEPAK SAKHARAM UMBARKAR",
        "contact_phone": "9820334455",
        "contact_designation": "Proprietor",
        "created_by_name": "Siddhi Kilaje",
        "task_created_date": date(2026, 9, 12),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Demo",
        "task_approved_by": None,
        "task_approved_date": None,
        "task_allotted_to": None,
        "payment_status": None,
        "status": "Pending",
        "completed_date": None,
    },
    {
        "company_name": "EVERY DAY TECHNO SOLUTIONS",
        "task_type": "In-House",
        "city": "Medchal-Malkajgiri",
        "third_party": None,
        "priority": "A",
        "machine_model": "DKX4540 Automatic Carton Erector",
        "task_description": "Bottom flap tape folding trial on corrugated master shipper cartons. High-speed cycle validation.",
        "contact_person_name": "Irfan",
        "contact_phone": "9248009902",
        "contact_designation": None,
        "created_by_name": "Dhairya Shah",
        "task_created_date": date(2026, 9, 17),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": None,
        "task_approved_date": None,
        "task_allotted_to": None,
        "payment_status": None,
        "status": "Pending",
        "completed_date": None,
    },
    {
        "company_name": "WHOLESOMEBASKET MARKETING PRIVATE LIMITED",
        "task_type": "Onsite Visit - Client Location",
        "city": "Mumbai",
        "third_party": None,
        "priority": "A",
        "machine_model": "GF100 Granular Filler",
        "task_description": "Volumetric cup filling calibration for organic grains and lentils. Sensor alignment required.",
        "contact_person_name": "Vikram Singhania",
        "contact_phone": "9820112233",
        "contact_designation": "Plant Manager",
        "created_by_name": "Dhairya Shah",
        "task_created_date": date(2026, 9, 17),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Repair",
        "task_approved_by": None,
        "task_approved_date": None,
        "task_allotted_to": None,
        "payment_status": None,
        "status": "Pending",
        "completed_date": None,
    },
    {
        "company_name": "INTEGRATED DRIVE SYSTEMS PRIVATE LIMITED",
        "task_type": "Telecall",
        "city": "Mumbai",
        "third_party": None,
        "priority": "A",
        "machine_model": "FR900 Band Sealer MSH With Nitrogen Kit",
        "task_description": "Gas flushing regulator setup and nitrogen nozzle timing guidance provided over video call.",
        "contact_person_name": "INTEGRATED DRIVE SYSTEMS PRIVATE LIMITED",
        "contact_phone": "9930199809",
        "contact_designation": None,
        "created_by_name": "Siddhi Kilaje",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Demo",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 17),
        "task_allotted_to": "Mangal Pandey",
        "payment_status": None,
        "status": "Approved",
        "completed_date": None,
    },
    {
        "company_name": "WHITE FALCON INTERNATIONAL",
        "task_type": "Telecall",
        "city": "Surat",
        "third_party": "Surat",
        "priority": "A",
        "machine_model": "AF1500SA Semi Automatic Auger Machine",
        "task_description": "Assistance with screw auger dosing parameters for protein powder formulation.",
        "contact_person_name": "Patel",
        "contact_phone": "8866080604",
        "contact_designation": None,
        "created_by_name": "Sunita Pawar",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 16),
        "task_allotted_to": "Devendra Marade",
        "payment_status": None,
        "status": "Approved",
        "completed_date": None,
    },
    {
        "company_name": "CERA-CHEM PRIVATE LIMITED",
        "task_type": "In-House",
        "city": "Kalol",
        "third_party": None,
        "priority": "A",
        "machine_model": "XM25.4 Handy Printer Metal Body 25.4 Mm",
        "task_description": "Batch coding test on HDPE bottles and HDPE woven sacks using quick-drying solvent ink.",
        "contact_person_name": "Bala Murali",
        "contact_phone": "9550658366",
        "contact_designation": "Manager",
        "created_by_name": "Bhavin Suthar",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Repair",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 17),
        "task_allotted_to": "Devendra Marade",
        "payment_status": None,
        "status": "Approved",
        "completed_date": None,
    },
    {
        "company_name": "Flick Packaging",
        "task_type": "Telecall",
        "city": "Ahmedabad",
        "third_party": None,
        "priority": "A",
        "machine_model": "FFS1000 Centre Sealer 420mm",
        "task_description": "Vertical seal temperature setting troubleshooting. Machine running at 60 packs per minute successfully.",
        "contact_person_name": "Ravi Shankar",
        "contact_phone": "8409817239",
        "contact_designation": None,
        "created_by_name": "Dhairya Shah",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Demo",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 16),
        "task_allotted_to": "Devendra Marade",
        "payment_status": None,
        "status": "Completed",
        "completed_date": date(2026, 9, 16),
    },
    {
        "company_name": "OM PACKAGING AUTOMATION",
        "task_type": "In-House",
        "city": "Panvel",
        "third_party": None,
        "priority": "A",
        "machine_model": "ISL150 Automatic Round Bottle Labelling Machine",
        "task_description": "Wrap-around self-adhesive sticker labelling trial on 500ml syrup bottles.",
        "contact_person_name": "Akhilesh Pandey",
        "contact_phone": "8169887438",
        "contact_designation": None,
        "created_by_name": "Dhairya Shah",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 16),
        "task_allotted_to": "Devendra Marade",
        "payment_status": None,
        "status": "Completed",
        "completed_date": date(2026, 9, 16),
    },
    {
        "company_name": "PURETICA FOODS ENTERPRISES",
        "task_type": "Telecall",
        "city": "Thane",
        "third_party": None,
        "priority": "A",
        "machine_model": "DBF900L Band Sealer MSH With Nitrogen Kit",
        "task_description": "Continuous band sealer conveyer speed regulation and sealing belt replacement guidance.",
        "contact_person_name": "NIKHIL ANIL SARVAGOD",
        "contact_phone": "9594373469",
        "contact_designation": None,
        "created_by_name": "Siddhi Kilaje",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 16),
        "task_allotted_to": "Devendra Pandey",
        "payment_status": None,
        "status": "Completed",
        "completed_date": date(2026, 9, 17),
    },
    {
        "company_name": "L COSMO H & P CARE",
        "task_type": "Onsite Visit - Client Location",
        "city": "Bhiwandi",
        "third_party": None,
        "priority": "A",
        "machine_model": "ISL350 Stacker Conveyor",
        "task_description": "Finished carton transport linkup between packaging station and pallet storage area.",
        "contact_person_name": "Pankaj Jain",
        "contact_phone": "9820556677",
        "contact_designation": "Operations Manager",
        "created_by_name": "Dhairya Shah",
        "task_created_date": date(2026, 9, 16),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Demo",
        "task_approved_by": "Parth Shah",
        "task_approved_date": date(2026, 9, 16),
        "task_allotted_to": "Devendra Pandey",
        "payment_status": None,
        "status": "Completed",
        "completed_date": date(2026, 9, 16),
    },
    {
        "company_name": "Tulika Machine Tools",
        "task_type": "In-House",
        "city": "Pimpri Chinchwad",
        "third_party": None,
        "priority": "A",
        "machine_model": "TDFJ160 Automatic Can Sealer MS",
        "task_description": "Can height chuck adjustment and roller spin test. Client postponed installation to next month.",
        "contact_person_name": "GUPTA SUNIL NANDLAL",
        "contact_phone": "9322775095",
        "contact_designation": None,
        "created_by_name": "Siddhi Kilaje",
        "task_created_date": date(2026, 9, 10),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 10),
        "task_allotted_to": "Mangal Pandey",
        "payment_status": None,
        "status": "Cancel",
        "completed_date": None,
    },
    {
        "company_name": "WHITE FALCON INTERNATIONAL",
        "task_type": "In-House",
        "city": "Surat",
        "third_party": "Surat",
        "priority": "A",
        "machine_model": "AF1500SA Semi Automatic Auger Machine",
        "task_description": "Auger funnel changeover request. Cancelled due to client material supply delay.",
        "contact_person_name": "Sunita Pawar",
        "contact_phone": "9820998877",
        "contact_designation": None,
        "created_by_name": "Sunita Pawar",
        "task_created_date": date(2026, 9, 9),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 9),
        "task_allotted_to": "Mukesh Paudwal",
        "payment_status": None,
        "status": "Cancel",
        "completed_date": None,
    },
    {
        "company_name": "SHIVAM ELECTRICALS",
        "task_type": "In-House",
        "city": "Rajkot",
        "third_party": None,
        "priority": "A",
        "machine_model": "ISL350XDAN Flow Wrap Machine W/O End Seal Chain",
        "task_description": "Horizontal flow wrapper test for electrical switch box wrapping. Cancelled due to duplicate task.",
        "contact_person_name": "Mayur Patel",
        "contact_phone": "7874780698",
        "contact_designation": None,
        "created_by_name": "Chirag Boda",
        "task_created_date": date(2026, 9, 2),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 9, 9),
        "task_allotted_to": "Mukesh Paudwal",
        "payment_status": None,
        "status": "Cancel",
        "completed_date": None,
    },
    {
        "company_name": "Kamal Packaging",
        "task_type": "In-House",
        "city": "Mumbai",
        "third_party": None,
        "priority": "A",
        "machine_model": "MT50 Semi Auto Labelling Machine",
        "task_description": "Bottle label applicator testing. Cancelled as client chose fully automatic ISL150 model instead.",
        "contact_person_name": "JAYASHREE WAMAN KAMBLE",
        "contact_phone": "8108752149",
        "contact_designation": None,
        "created_by_name": "Siddhi Kilaje",
        "task_created_date": date(2026, 8, 20),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Trial",
        "task_approved_by": "Sushant Dhawade",
        "task_approved_date": date(2026, 8, 20),
        "task_allotted_to": "Mangal Pandey",
        "payment_status": None,
        "status": "Cancel",
        "completed_date": None,
    },
    {
        "company_name": "BAHUCHAR SALES AGENCY",
        "task_type": "Telecall",
        "city": "Ahmedabad",
        "third_party": None,
        "priority": "A",
        "machine_model": "DGYF500C Portable Induction Sealer",
        "task_description": "Induction head coil overheating issue reported. Resolved over phone with power stabilization guide.",
        "contact_person_name": "Anil Sir",
        "contact_phone": "9825010335",
        "contact_designation": "Owner",
        "created_by_name": "Bhavin Suthar",
        "task_created_date": date(2026, 8, 20),
        "service_type": "Free",
        "service_charge": None,
        "call_type": "Repair",
        "task_approved_by": "Parth Shah",
        "task_approved_date": date(2026, 8, 20),
        "task_allotted_to": "Mangal Pandey",
        "payment_status": None,
        "status": "Cancel",
        "completed_date": None,
    },
]

async def seed():
    sessionmaker = get_sessionmaker()
    async with sessionmaker() as session:
        # Check existing
        existing_res = await session.execute(select(TechnicalTask.company_name))
        existing_companies = set(existing_res.scalars().all())

        added = 0
        for task_data in SAMPLE_TASKS:
            task = TechnicalTask(
                id=uuid.uuid4(),
                **task_data,
            )
            session.add(task)
            added += 1

        await session.commit()
        print(f"Successfully seeded {added} technical task records.")

if __name__ == "__main__":
    asyncio.run(seed())
