search-path = ["backend"]
infer-with-first-use = false
python-interpreter-path = "C:/Users/Inhyma Solutions/AppData/Local/Programs/Python/Python312/python.exe"
site-package-path = [
    "C:/Users/Inhyma Solutions/AppData/Local/Programs/Python/Python312/Lib/site-packages",
    "backend/.venv/Lib/site-packages"
]

