import type { SaleOrder, SaleSummaryMetrics } from "@/types/saleProcess";

// Production empty KPI metrics
export const EMPTY_METRICS: SaleSummaryMetrics = {
  all: { count: 0, amount: 0.0 },
  admin_confirmed_to_lr: { count: 0, amount: 0.0 },
  pending: { count: 0, amount: 0.0 },
  admin_approved: { count: 0, amount: 0.0 },
  lr: { count: 0, amount: 0.0 },
  cancelled: { count: 0, amount: 0.0 },
  sales_confirmed: { count: 0, amount: 0.0 },
  acc_confirmed: { count: 0, amount: 0.0 },
  gatepass_created: { count: 0, amount: 0.0 },
  dispatched: { count: 0, amount: 0.0 },
  gatepass_cancelled: { count: 0, amount: 0.0 },
};

export const MOCK_METRICS: SaleSummaryMetrics = {
  all: { count: 4762, amount: 299107379.78 },
  admin_confirmed_to_lr: { count: 4745, amount: 295511129.78 },
  pending: { count: 2, amount: 342650.0 },
  admin_approved: { count: 8, amount: 3248200.0 },
  lr: { count: 4682, amount: 284336441.78 },
  cancelled: { count: 0, amount: 0.0 },
  sales_confirmed: { count: 15, amount: 1250000.0 },
  acc_confirmed: { count: 4, amount: 480000.0 },
  gatepass_created: { count: 14, amount: 1650000.0 },
  dispatched: { count: 37, amount: 2890000.0 },
  gatepass_cancelled: { count: 0, amount: 0.0 },
};

export const INITIAL_METRICS: SaleSummaryMetrics =
  import.meta.env.MODE === "test" ? MOCK_METRICS : EMPTY_METRICS;

// Test fixtures for vitest suite
const TEST_SALE_ORDERS: SaleOrder[] = [
  {
    id: "so-4041",
    order_no: "SO-MH/26-27/4041",
    order_date: "21-09-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "21-09-2026",
    company_name: "V S Machines",
    city: "Navi Mumbai",
    state: "Maharashtra",
    third_party: "No",
    po: "No",
    sales_person: "Dhairya Shah",
    amount_inc_gst: 271400.0,
    amount_exc_gst: 230000.0,
    discount: 0.0,
    status: "pending",
    status_updated_at: null,
    acc_dep: "Timeline",
    gatepass: "Pending",
    buyer_name: "V S Machines",
    billing_address:
      "Plot No. PAP-K-37, TTC INDL Area Digha, Airoli Nr. Yadav Nagar (Shynu Hotel) Airoli, Navi Mumbai, Maharashtra, 400708",
    shipping_address:
      "Plot No. PAP-K-37, TTC INDL Area Digha, Airoli Nr. Yadav Nagar (Shynu Hotel) Airoli, Navi Mumbai, Maharashtra, 400708",
    phone: "9820402017",
    gst_no: "27AAOFV6626B3ZZ",
    transport_name: "Self Pickup",
    payment_terms: "30 Days Credit",
    exp_dispatch_date: "21-09-2026",
    created_at: "21-09-2026 11:24 AM",
    total_amount: 271400.0,
    total_basic: 230000.0,
    total_tax: 41400.0,
    total_quantity: 1,
    item_count: 1,
    items: [
      {
        product_name: "ISL350XDAN Flow Wrap Machine W/D End Seal Chain",
        hsn_code: "8422.30.00",
        quantity: 1,
        unit_rate: 230000.0,
        tax_percent: 18,
        tax_amount: 41400.0,
        item_total: 271400.0,
        product_id: null,
      },
    ],
    terms: [
      "1. Transport Charges: To Pay.",
      "2. Payment Terms: 100% Before Dispatch.",
      "3. Order Once Confirmed, Cannot Be Cancelled.",
    ],
    files: [
      { name: "Sales_Order_SO-MH_26-27_4041.pdf", size: "148 KB", type: "application/pdf" },
      { name: "Buyer_Purchase_Order_VS_Machines.pdf", size: "215 KB", type: "application/pdf" },
      { name: "Gatepass_Self_Pickup_Draft.pdf", size: "96 KB", type: "application/pdf" },
    ],
  },
  {
    id: "so-3826",
    order_no: "SO-MH/26-27/3826",
    order_date: "12-09-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "12-09-2026",
    company_name: "GARUDA ENGINEERS",
    city: "Ahmedabad",
    state: "Gujarat",
    third_party: "No",
    po: "No",
    sales_person: "Abhishek Patel",
    amount_inc_gst: 324500.0,
    amount_exc_gst: 275000.0,
    discount: 35000.0,
    status: "lr",
    status_updated_at: "16-09-2026 12:51 PM",
    acc_dep: "Timeline",
    gatepass: "4539",
    buyer_name: "GARUDA ENGINEERS",
    billing_address:
      "Shed No C-15, Maruti Industrial Estate, Phase 1, Narol Vatwa Road, Ahmedabad, Ahmedabad, Ahmedabad, Maharashtra,",
    shipping_address:
      "Shed No C-15, Maruti Industrial Estate, Phase 1, Narol Vatwa Road, Ahmedabad, Ahmedabad, Ahmedabad, Maharashtra,",
    phone: "9427419237",
    gst_no: "24ALCPG8895N1ZG",
    contact_person_name: "Jalpesh",
    contact_person_mobile: "9427419237",
    transport_name: "Delhivery Limited",
    transporter_gst: "06AAPCS9575E1ZR",
    delivery_type: "godown",
    delivery_charge: "To Pay",
    payment_terms: "100% Advance",
    exp_dispatch_date: "12-09-2026",
    created_at: "12-09-2026 11:26 AM",
    total_amount: 324500.0,
    total_basic: 310000.0,
    total_tax: 49500.0,
    total_quantity: 1,
    item_count: 1,
    items: [
      {
        product_name: "ISL450XDAN Flow Wrap machine with end seal chain",
        hsn_code: "8422.30.00",
        quantity: 1,
        unit_rate: 310000.0,
        tax_percent: 18,
        tax_amount: 49500.0,
        item_total: 324500.0,
        product_id: null,
      },
    ],
    terms: [
      "1. Transport Charges: To Pay.",
      "2. Payment Terms: 100% Before Dispatch.",
      "3. Order once confirmed, cannot be cancelled.",
    ],
    files: [
      { name: "Sales_Order_SO-MH_26-27_3826.pdf", size: "151 KB", type: "application/pdf" },
      { name: "Buyer_Purchase_Order_Garuda_Engineers.pdf", size: "215 KB", type: "application/pdf" },
      { name: "Gatepass_4539.pdf", size: "96 KB", type: "application/pdf" },
    ],
  },
  {
    id: "so-3787",
    order_no: "SO-MH/26-27/3787",
    order_date: "11-09-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "11-09-2026",
    company_name: "Annie Packaging (S)",
    city: "Madhubani",
    state: "Bihar",
    third_party: "No",
    po: "No",
    sales_person: "Abhishek Patel",
    amount_inc_gst: 132927.0,
    amount_exc_gst: 112650.0,
    discount: 0.0,
    status: "pending",
    status_updated_at: null,
    acc_dep: "Timeline",
    buyer_name: "Annie Packaging (S)",
    total_amount: 132927.0,
    total_quantity: 2,
    item_count: 2,
  },
  {
    id: "so-0807",
    order_no: "SO-GJ/26-27/0807",
    order_date: "21-09-2026",
    warehouse: "Ahmedabad",
    expected_delivery_date: "21-09-2026",
    company_name: "AAVJO INDUSTRIES",
    city: "Ahmedabad",
    state: "Gujarat",
    third_party: "No",
    po: "No",
    sales_person: "Siddhi Kilaje",
    amount_inc_gst: 99120.0,
    amount_exc_gst: 84000.0,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "21-09-2026 04:22 PM",
    acc_dep: "Timeline",
    buyer_name: "AAVJO INDUSTRIES",
    total_amount: 99120.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-4068",
    order_no: "SO-MH/26-27/4068",
    order_date: "21-09-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "21-09-2026",
    company_name: "NEWEDGE METALCRAFT MHE LLP",
    city: "Palghar",
    state: "Maharashtra",
    third_party: "No",
    po: "No",
    sales_person: "Sunita Pawar",
    amount_inc_gst: 18880.0,
    amount_exc_gst: 16000.0,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "21-09-2026 04:22 PM",
    acc_dep: "Timeline",
    buyer_name: "NEWEDGE METALCRAFT MHE LLP",
    total_amount: 18880.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-4067",
    order_no: "SO-MH/26-27/4067",
    order_date: "21-09-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "21-09-2026",
    company_name: "SHREE HARI TRADERS",
    city: "Rajkot",
    state: "Gujarat",
    third_party: "No",
    po: "No",
    sales_person: "Bhavin Suthar",
    amount_inc_gst: 7788.0,
    amount_exc_gst: 6600.0,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "21-09-2026 04:22 PM",
    acc_dep: "Timeline",
    buyer_name: "SHREE HARI TRADERS",
    total_amount: 7788.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-4065",
    order_no: "SO-MH/26-27/4065",
    order_date: "21-09-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "21-09-2026",
    company_name: "Mahadev Enterprises (M)",
    city: "Kalyan-Dombivli",
    state: "Maharashtra",
    third_party: "No",
    po: "No",
    sales_person: "Siddhi Kilaje",
    amount_inc_gst: 333940.0,
    amount_exc_gst: 283000.0,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "21-09-2026 04:03 PM",
    acc_dep: "Timeline",
    buyer_name: "Mahadev Enterprises (M)",
    total_amount: 333940.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-4064",
    order_no: "SO-MH/26-27/4064",
    order_date: "21-09-2026",
    warehouse: "Mumbai Transit",
    expected_delivery_date: "21-09-2026",
    company_name: "VB Techno",
    city: "Bhavnagar",
    state: "Gujarat",
    third_party: "No",
    po: "No",
    sales_person: "Dhairya Shah",
    amount_inc_gst: 120360.0,
    amount_exc_gst: 102000.0,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "21-09-2026 03:59 PM",
    acc_dep: "Timeline",
    buyer_name: "VB Techno",
    total_amount: 120360.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-4016",
    order_no: "SO-MH/26-27/4016",
    order_date: "18-09-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "18-09-2026",
    company_name: "MANDAGINI SEALS",
    city: "Chennai",
    state: "Tamil Nadu",
    third_party: "No",
    po: "No",
    sales_person: "Dhairya Shah",
    amount_inc_gst: 153400.0,
    amount_exc_gst: 130000.0,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "18-09-2026 07:33 PM",
    acc_dep: "Timeline",
    gatepass: "Pending",
    buyer_name: "MANDAGINI SEALS",
    total_amount: 153400.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-0709",
    order_no: "SO-GJ/26-27/0709",
    order_date: "10-09-2026",
    warehouse: "Ahmedabad",
    expected_delivery_date: "10-09-2026",
    company_name: "ROXIS PACKAGING LLP",
    city: "Ahmedabad",
    state: "Gujarat",
    third_party: "No",
    po: "No",
    sales_person: "Dhairya Shah",
    amount_inc_gst: 274640.0,
    amount_exc_gst: 232745.76,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "10-09-2026 12:17 PM",
    acc_dep: "Timeline",
    gatepass: "Pending",
    buyer_name: "ROXIS PACKAGING LLP",
    total_amount: 274640.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-3916",
    order_no: "SO-MH/26-27/3916",
    order_date: "16-09-2026",
    warehouse: "Mumbai Transit",
    expected_delivery_date: "16-09-2026",
    company_name: "AVP INDIA LIFTING AND PACKAGING SOLUTIONS",
    city: "Pune",
    state: "Maharashtra",
    third_party: "No",
    po: "No",
    sales_person: "Sunita Pawar",
    amount_inc_gst: 101480.0,
    amount_exc_gst: 86000.0,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "16-09-2026 01:55 PM",
    acc_dep: "Timeline",
    gatepass: "Pending",
    buyer_name: "AVP INDIA LIFTING AND PACKAGING SOLUTIONS",
    total_amount: 101480.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-3915",
    order_no: "SO-MH/26-27/3915",
    order_date: "16-09-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "12-09-2026",
    company_name: "AVP INDIA LIFTING AND PACKAGING SOLUTIONS",
    city: "Pune",
    state: "Maharashtra",
    third_party: "No",
    po: "No",
    sales_person: "Sunita Pawar",
    amount_inc_gst: 153400.0,
    amount_exc_gst: 130000.0,
    discount: 0.0,
    status: "sales_confirmed",
    status_updated_at: "16-09-2026 01:55 PM",
    acc_dep: "Timeline",
    gatepass: "Pending",
    buyer_name: "AVP INDIA LIFTING AND PACKAGING SOLUTIONS",
    total_amount: 153400.0,
    total_quantity: 1,
    item_count: 1,
  },
  {
    id: "so-3476",
    order_no: "SO-MH/26-27/3476",
    order_date: "31-08-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "31-08-2026",
    company_name: "PACKNCODE SYSTEMS",
    city: "Mumbai",
    state: "Maharashtra",
    third_party: "No",
    po: "No",
    sales_person: "Dhairya Shah",
    amount_inc_gst: 11800.0,
    amount_exc_gst: 10000.0,
    discount: 0.0,
    status: "admin_approved",
    status_updated_at: "31-08-2026 12:29 PM",
    acc_dep: "Timeline",
    gatepass: "Pending",
    buyer_name: "PACKNCODE SYSTEMS",
    total_amount: 11800.0,
    total_basic: 10000.0,
    total_tax: 1800.0,
    total_quantity: 1,
    item_count: 1,
    timeline: [
      {
        status: "Admin Approved",
        date: "31-08-2026 12:29 PM",
        by: "Dhairya Shah",
      },
      {
        status: "Sales Confirmed",
        date: "31-08-2026 12:29 PM",
        by: "Dhairya Shah",
      },
      {
        status: "Pending",
        date: "31-08-2026 12:29 PM",
        by: "Dhairya Shah",
        remark:
          "Bill Abhi Mat Banana. Next Week taka Stock Ayega Tab Bill Banana Hai. Abhi Dispatch Karna Hai",
      },
    ],
  },
  {
    id: "so-4669",
    order_no: "SO-MH/26-27/4669",
    order_date: "31-08-2026",
    warehouse: "Mumbai",
    expected_delivery_date: "31-08-2026",
    company_name: "PACKNCODE SYSTEMS",
    city: "Mumbai",
    state: "Maharashtra",
    third_party: "No",
    po: "No",
    sales_person: "Dhairya Shah",
    amount_inc_gst: 11800.0,
    amount_exc_gst: 10000.0,
    discount: 0.0,
    status: "admin_approved",
    status_updated_at: "31-08-2026 12:29 PM",
    acc_dep: "Timeline",
    gatepass: "Pending",
    buyer_name: "PACKNCODE SYSTEMS",
    total_amount: 11800.0,
    total_basic: 10000.0,
    total_tax: 1800.0,
    total_quantity: 1,
    item_count: 1,
    timeline: [
      {
        status: "Admin Approved",
        date: "31-08-2026 12:29 PM",
        by: "Dhairya Shah",
      },
      {
        status: "Sales Confirmed",
        date: "31-08-2026 12:29 PM",
        by: "Dhairya Shah",
      },
      {
        status: "Pending",
        date: "31-08-2026 12:29 PM",
        by: "Dhairya Shah",
        remark:
          "Bill Abhi Mat Banana. Next Week taka Stock Ayega Tab Bill Banana Hai. Abhi Dispatch Karna Hai",
      },
    ],
  },
];

export const INITIAL_SALE_ORDERS: SaleOrder[] =
  import.meta.env.MODE === "test" ? TEST_SALE_ORDERS : [];
